// @amps-ui/ui -- shadcn/ui primitives + Tailwind v4 theme tokens.
//
// M3B (plan §7, §5): Tailwind v4 via `@tailwindcss/vite` (not PostCSS), theme
// tokens and component source generated by the shadcn CLI and vendored here
// under `src/components/ui`. Exports exactly the components actually used
// by the shell and the feature packages: button, badge, dialog, alert,
// tooltip, separator, dropdown-menu, sonner (toaster). M7 (`plan/notes/
// M7-ux-design.md` §9) adds `skeleton` (first-load placeholder rows).
//
// PATH-ALIAS NOTE (plan §2, §7 M3B: "expect to hand-fix the shadcn path
// aliases -- the CLI assumes a single-package app"): the shadcn CLI's
// framework detection requires a real Vite app (a `vite.config.ts` +
// resolvable `@tailwindcss/vite` + a `@/*` tsconfig alias) to run `init`/
// `add` against. This package has none of those -- it is a source-only
// library consumed directly by `apps/trading-ui`'s Vite build, with no
// bundler of its own (plan §1: "no per-package build step"). So components
// were generated once in a throwaway scratch Vite app (see `components.json`
// for the exact style/base-color/alias configuration used) and vendored
// here with their `@/...` imports hand-rewritten to plain relative imports
// -- there is no alias to resolve at build time, only files next to each
// other in this package. `components.json` is kept for provenance and so a
// future `shadcn diff`/`add` can be re-run the same way.
//
// Depends on: React, `radix-ui`, `cn`, `class-variance-authority`,
// `lucide-react`, `sonner`, `next-themes`, `tailwindcss`, `tw-animate-css`.
// Consumed by: `apps/trading-ui/src/shell`, and (once built) by
// `@amps-ui/feature-orders` / `@amps-ui/feature-order-details`.
export { Alert, AlertDescription, AlertTitle } from './components/ui/alert';
export { Badge, badgeVariants } from './components/ui/badge';
export { Button, buttonVariants } from './components/ui/button';
export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from './components/ui/dialog';
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from './components/ui/dropdown-menu';
export { Separator } from './components/ui/separator';
export { Skeleton } from './components/ui/skeleton';
export { Toaster } from './components/ui/sonner';
// Re-exported (rather than each consumer depending on `sonner` directly) so
// this package stays the one place that owns "how a toast looks/behaves" --
// plan §5/M5: "error events surfaced as shadcn toasts".
export { toast } from 'sonner';
export {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from './components/ui/tooltip';
